### ISSUE TITLE
BOM file

### ISSUE THREAD

**Issue by happytm** [MakerM0/MagiClick#1]
Great project for great chip. 

Instead of using USB-C, I want to use directly plugged USB-A PCB for simplicity. Is it OK to program the chip with USB-A PCB? If So what pins should I use? 

Can you please publish BOM file or parts list?

Thanks.

**Comment by MakerM0** [comment]
Thanks！
It can be replaced with USB-A, and there is basically no need to modify the line.
I'll update the BOM to the repository later.

**Comment by happytm** [comment]
Thank you for your quick reply.

**Comment by happytm** [comment]
@MakerM0 Can you please publish .sch and .pcb files for main PCB with CH582F chip on it? If not can you advice me how to achieve following goals?

1. I wanted to build lowest cost BLE board to test 1KM range of chip using coded PHY @125K.
2. I wanted to remove USB-C type connector and use USB-A pcb type connector for simplicity and low cost. 
3. I wanted to provide pads for SMA/UFL connector for external antenna to test long range of this chip.
4. If possible, I would like to get rid of any external LDO and use only button cell battery for testing and while flashing the 
   board I can use couple of diaodes on board to drop voltage of 5V to 3.6V. Or is there any other way to drop voltage when 
   flashing?
5. I will be adding NTC thermistor and analog light sensor on board and send this data via BLE. If you know any inexpensive 
   parts for this purpose please let me know.
6. Hopefully, all these can fit on 20x20 mm board without pcb antenna.

I tried to recreate project from your PDF schematics but I am not very good at creating PCB from scratch and routing it properly.

I have implemented ultra low power home automation solution based on ESP32 :  https://github.com/happytm/BatteryNode  but this chip can help create even lower power home automation network.

I will appreciate any help or advice you can provide.
Thank you.

**Comment by MakerM0** [comment]
@happytm Sorry, I am using an EDA software that does not support exporting files in this format.

USB-A is OK.
The LDO can be removed and replaced with several diodes.
I don't have a suitable sensor to recommend.
This size 20X20 should be easily satisfied.

**Comment by happytm** [comment]
Thank you.
